# Generated by Django 4.2.1 on 2023-08-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='leader',
            field=models.CharField(default='', max_length=200),
        ),
    ]
