# Generated by Django 4.2.1 on 2023-08-31 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APapp', '0002_useraccount_leader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='name',
            new_name='Tname',
        ),
    ]
