# Generated by Django 4.2.1 on 2023-08-31 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APapp', '0003_rename_name_useraccount_tname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='Tname',
            new_name='name',
        ),
    ]
