# Generated by Django 4.2.1 on 2023-09-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APapp', '0007_useraccount_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='organisation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
