# Generated by Django 4.2.1 on 2023-09-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APapp', '0008_useraccount_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='organisation',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
